// <auto-generated />
namespace QuotesAPI2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class datetimadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetimadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202105210903155_datetimadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
